import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { serviceAreas, services, site } from "@/lib/site";
import styles from "../../site.module.css";
export function generateStaticParams(){return serviceAreas.map(area=>({city:area.slug}));}
export async function generateMetadata({params}:{params:Promise<{city:string}>}){const {city}=await params;const area=serviceAreas.find(x=>x.slug===city);return area?{title:`Custom Embroidery, Screen Printing & DTF in ${area.name}, TX`,description:`Embro Xpress serves ${area.name}, TX with custom embroidery, screen printing, and DTF printing from our McAllen shop.`}:{}}
export default async function CityPage({params}:{params:Promise<{city:string}>}){const {city}=await params;const area=serviceAreas.find(x=>x.slug===city);if(!area)notFound();return <div className={styles.shell}><SiteHeader/><main><section className={styles.pageHero}><p className={styles.crumbs}><Link href="/">Home</Link> / <Link href="/service-areas">RGV Service Areas</Link> / {area.name}</p><p className={styles.kicker}>Serving {area.name}, Texas</p><h1>Custom apparel<br /><span>for {area.name}.</span></h1><p>{area.copy}</p></section><section className={styles.contentGrid}><article className={styles.prose}><h2>Custom embroidery, screen printing, and DTF for {area.name}</h2><p>Embro Xpress helps businesses, teams, schools, and organizations connect their logo to the apparel they wear. Our McAllen shop serves the broader Rio Grande Valley, including {area.name}.</p><h2>Explore project options</h2><ul>{services.map(service=><li key={service.slug}><Link className={styles.textLink} href={`/services/${service.slug}`}>{service.name}</Link> — {service.summary}</li>)}</ul><h2>A Rio Grande Valley shop, not a generic online printer</h2><p>Working with a regional apparel-decoration shop means you can start a real conversation about your logo, garments, and project needs. Call our McAllen location or message our Facebook page to get started.</p></article><aside className={styles.sidebar}><h2>Talk to Embro Xpress</h2><a href={site.phoneHref}>Call {site.phone}</a><a href={site.maps} target="_blank" rel="noreferrer">McAllen shop directions ↗</a><a href={site.facebook} target="_blank" rel="noreferrer">Facebook ↗</a></aside></section></main><SiteFooter/></div>}
